version: '3.9'

services:
  postgres:
    image: postgres:13.4
    ports:
      - published: 5432
        target: 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
